# Generated by Django 3.2.5 on 2021-08-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameField', models.CharField(help_text='Enter a username', max_length=20)),
                ('passwordField', models.CharField(help_text='Enter a password', max_length=20)),
            ],
        ),
    ]
