# Generated by Django 3.2.5 on 2021-08-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodel',
            old_name='passwordField',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='loginmodel',
            old_name='usernameField',
            new_name='username',
        ),
    ]
