# Generated by Django 3.2.5 on 2021-08-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_customusermodel_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_staff',
        ),
    ]
